services:
  farola-api:
    build: .
    container_name: farola-api
    depends_on:
      postgres-db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Database=Farola;Username=postgres;Password=FarolaPassword123;Include Error Detail=true
      - ConnectionStrings__Redis=redis:6379
    # Добавить сеть
    networks:
      - farola-network

  postgres-db:
    image: postgres:16
    container_name: farola-postgres
    environment:
      POSTGRES_PASSWORD: FarolaPassword123
      POSTGRES_DB: Farola
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d Farola"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - farola-network

  redis:
    image: redis:alpine
    container_name: farola-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - farola-network

  nginx:
    image: nginx:alpine
    container_name: farola-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - farola-api
    networks:
      - farola-network

networks:
  farola-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: