// <auto-generated />
using System;
using Farola.Infrastructure.Data.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Farola.Infrastructure.Migrations
{
    [DbContext(typeof(FarolaDbContext))]
    partial class FarolaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Farola.Domain.Entities.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id")
                        .HasComment("Номер клиента");

                    b.Property<int>("ProfessionalId")
                        .HasColumnType("integer")
                        .HasColumnName("professional_id")
                        .HasComment("Номер специалиста");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ProfessionalId", "ClientId")
                        .IsUnique()
                        .HasDatabaseName("ix_favorites_professional_client");

                    b.ToTable("favorites", null, t =>
                        {
                            t.HasComment("Таблица избранных специалистов");
                        });
                });

            modelBuilder.Entity("Farola.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasComment("Идентификатор токена");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("Дата и время создания");

                    b.Property<string>("DeviceFingerprint")
                        .HasColumnType("text");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiresat")
                        .HasComment("Дата и время истечения срока действия");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token")
                        .HasComment("Токен");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userid")
                        .HasComment("Идентификатор пользователя");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token");

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", null, t =>
                        {
                            t.HasComment("Токены обновления");
                        });
                });

            modelBuilder.Entity("Farola.Domain.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasComment("Идентификатор отзыва");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_added")
                        .HasDefaultValueSql("now()")
                        .HasComment("Дата добавления");

                    b.Property<float>("Grade")
                        .HasColumnType("real")
                        .HasColumnName("grade")
                        .HasComment("Оценка работы");

                    b.Property<int>("StatementId")
                        .HasColumnType("integer")
                        .HasColumnName("statement_id")
                        .HasComment("Номер заявления");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text")
                        .HasComment("Текст отзыва");

                    b.HasKey("Id");

                    b.HasIndex("StatementId");

                    b.ToTable("reviews", null, t =>
                        {
                            t.HasComment("Таблица отзывов клиентов");
                        });
                });

            modelBuilder.Entity("Farola.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasComment("Идентификатор роли");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("name")
                        .HasComment("Наименование роли");

                    b.HasKey("Id");

                    b.ToTable("roles", null, t =>
                        {
                            t.HasComment("Справочник ролей пользователей");
                        });
                });

            modelBuilder.Entity("Farola.Domain.Entities.Specialization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasComment("Идентификатор специализации");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name")
                        .HasComment("Наименование специализации");

                    b.Property<string>("Photo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("photo")
                        .HasComment("Фото специализации");

                    b.HasKey("Id");

                    b.ToTable("specializations", null, t =>
                        {
                            t.HasComment("Справочник специализаций");
                        });
                });

            modelBuilder.Entity("Farola.Domain.Entities.Statement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasComment("Идентификатор заявления");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id")
                        .HasComment("Номер клиента");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment")
                        .HasComment("Комментарий специалиста");

                    b.Property<DateTime>("DateAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_added")
                        .HasDefaultValueSql("now()")
                        .HasComment("Дата создания");

                    b.Property<DateTime?>("DateExpiration")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_expiration")
                        .HasComment("Дата закрытия заявки");

                    b.Property<float?>("Grade")
                        .HasColumnType("real")
                        .HasColumnName("grade")
                        .HasComment("Оценка специалиста на заказ");

                    b.Property<int>("ProfessionalId")
                        .HasColumnType("integer")
                        .HasColumnName("professional_id")
                        .HasComment("Номер специалиста");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id")
                        .HasComment("Номер статуса заявления");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_statements_client_id");

                    b.HasIndex("ProfessionalId")
                        .HasDatabaseName("ix_statements_professional_id");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("ix_statements_status_id");

                    b.ToTable("statements", null, t =>
                        {
                            t.HasComment("Таблица заявлений");
                        });
                });

            modelBuilder.Entity("Farola.Domain.Entities.StatementStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasComment("Идентификатор статуса заявления");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("name")
                        .HasComment("Наименование статуса");

                    b.HasKey("Id");

                    b.ToTable("statement_statuses", null, t =>
                        {
                            t.HasComment("Справочник статусов заявлений");
                        });
                });

            modelBuilder.Entity("Farola.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasComment("Идентификатор пользователя");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("area")
                        .HasComment("Место работы");

                    b.Property<DateTime>("DateRegistration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_registration")
                        .HasDefaultValueSql("now()")
                        .HasComment("Дата регистрации");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email")
                        .HasComment("Электронная почта");

                    b.Property<string>("Information")
                        .HasColumnType("text")
                        .HasColumnName("information")
                        .HasComment("Подробная информация");

                    b.Property<bool>("IsClosed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_closed")
                        .HasComment("Статус профиля специалиста (открыт/закрыт)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name")
                        .HasComment("Имя пользователя");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password")
                        .HasComment("Пароль");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("patronymic")
                        .HasComment("Отчество");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number")
                        .HasComment("Номер телефона");

                    b.Property<string>("Photo")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("photo")
                        .HasComment("Имя фото");

                    b.Property<string>("Profession")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("profession")
                        .HasComment("Профессия");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id")
                        .HasComment("Номер роли");

                    b.Property<int?>("SpecializationId")
                        .HasColumnType("integer")
                        .HasColumnName("specialization_id")
                        .HasComment("Номер специализации");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("surname")
                        .HasComment("Фамилия пользователя");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_users_phone");

                    b.HasIndex("RoleId");

                    b.HasIndex("SpecializationId");

                    b.ToTable("users", null, t =>
                        {
                            t.HasComment("Таблица пользователей системы");
                        });
                });

            modelBuilder.Entity("Farola.Domain.Entities.Favorite", b =>
                {
                    b.HasOne("Farola.Domain.Entities.User", "Client")
                        .WithMany("FavoriteClients")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_favorite_client");

                    b.HasOne("Farola.Domain.Entities.User", "Professional")
                        .WithMany("FavoriteProfessionals")
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_favorite_professional");

                    b.Navigation("Client");

                    b.Navigation("Professional");
                });

            modelBuilder.Entity("Farola.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Farola.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_token_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Farola.Domain.Entities.Review", b =>
                {
                    b.HasOne("Farola.Domain.Entities.Statement", "Statement")
                        .WithMany("Reviews")
                        .HasForeignKey("StatementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_review_statement");

                    b.Navigation("Statement");
                });

            modelBuilder.Entity("Farola.Domain.Entities.Statement", b =>
                {
                    b.HasOne("Farola.Domain.Entities.User", "Client")
                        .WithMany("StatementsAsClient")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_statement_client");

                    b.HasOne("Farola.Domain.Entities.User", "Professional")
                        .WithMany("StatementsAsProfessional")
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_statement_professional");

                    b.HasOne("Farola.Domain.Entities.StatementStatus", "Status")
                        .WithMany("Statements")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_statement_status");

                    b.Navigation("Client");

                    b.Navigation("Professional");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Farola.Domain.Entities.User", b =>
                {
                    b.HasOne("Farola.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_role");

                    b.HasOne("Farola.Domain.Entities.Specialization", "Specialization")
                        .WithMany("Users")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_user_specialization");

                    b.Navigation("Role");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("Farola.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Farola.Domain.Entities.Specialization", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Farola.Domain.Entities.Statement", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Farola.Domain.Entities.StatementStatus", b =>
                {
                    b.Navigation("Statements");
                });

            modelBuilder.Entity("Farola.Domain.Entities.User", b =>
                {
                    b.Navigation("FavoriteClients");

                    b.Navigation("FavoriteProfessionals");

                    b.Navigation("RefreshTokens");

                    b.Navigation("StatementsAsClient");

                    b.Navigation("StatementsAsProfessional");
                });
#pragma warning restore 612, 618
        }
    }
}
